### get all recipes
GET http://localhost:8080/recipes

### get all ingredients
GET http://localhost:8080/ingredients
Accept: application/json

### post a new ingredient
POST http://localhost:8080/ingredients
Content-Type: application/json

{
  "name" : "krumpli"
}

### response with bad request (empty name for the ingredient when posting)
POST http://localhost:8080/ingredients
Content-Type: application/json

{
  "name" : ""
}


### post a new recipe
POST http://localhost:8080/recipes
Content-Type: application/json

{
  "name" : "krumplistészta",
  "recipeType": "EBÉD",
  "text": "készítsünk krumplistésztát",
  "ingredientNames": [
    "hagyma", "krumpli", "tészta", "olaj"
  ]}

### response with bad request - ingredientNames are empty when posting a recipe

POST http://localhost:8080/recipes
Content-Type: application/json

{
"name" : "krumpistészta",
"recipeType": "EBÉD",
"text": "készítsünk krumplistésztát",
"ingredientNames": [

]}




