drop table if exists ingredient cascade
drop table if exists recipe cascade
drop table if exists recipes_ingredients cascade
drop sequence if exists ingredient_seq
create sequence ingredient_seq start with 1 increment by 50


create table ingredient
(
    id   bigint not null,
    name varchar(255),
    primary key (id)
)


create table recipe
(
    id          long generated by default as identity,
    name        varchar(255),
    recipe_type enum('REGGELI', 'TÍZÓRAI', 'EBÉD', 'UZSONNA', 'VACSORA'),
    text        varchar(255),
    primary key (id)
)


create table recipes_ingredients
(
    recipe_id     long not null,
    ingredient_id long not null,
    primary key (recipe_id, ingredient_id)
)


alter table if exists recipes_ingredients
    add constraint FKcp2atnubp9ilmmv2mqc0iw4jx
    foreign key (ingredient_id)
    references ingredient


alter table if exists recipes_ingredients
    add constraint FKm45ukcqooglgns0g1jirqywk1
    foreign key (recipe_id)
    references recipe